dbt_duckdb_delta:
  outputs:
    dev:
      type: duckdb
      #TODO make path relativ in the config?
      path: /home/aleks/git/open-source/dbt-duckdb-delta-plugin-demo/dbt_duckdb_delta/data/dbt.duckdb
      plugins: 
        - module: delta
        
  target: dev